import fs from 'fs'
import path from 'path'

import { simulateFrom, type MatchState, type OutcomeDistribution } from '@/lib/engine/kernel'
import { getEngineParams, getMatchAnchor, type MatchAnchor } from '@/lib/engine/params'

/**
 * Parity tests for the Match Engine kernel port.
 *
 * The committed fixture (`fixtures/parity.json`, generated by
 * `python -m backend.scripts.export_engine_kernel`) pins the TypeScript DP
 * to the Python reference to 1e-6 per probability. These tests execute the
 * REAL committed kernel artifact (`backend/data/engine/kernel.json`) — the
 * exact weights production serves.
 */

interface ParityCase {
  name: string
  anchor: MatchAnchor
  state: MatchState
  expected: OutcomeDistribution
}

interface ParityFixture {
  schema: number
  tolerance: number
  cases: ParityCase[]
}

const fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'parity.json'), 'utf-8')
) as ParityFixture

describe('engine kernel parity with the Python reference', () => {
  it('has the committed kernel artifact and fixture available', () => {
    expect(getEngineParams()).not.toBeNull()
    expect(fixture.cases.length).toBeGreaterThanOrEqual(20)
  })

  it.each(fixture.cases.map((c) => [c.name, c] as const))(
    'matches Python within %s tolerance: %s',
    (_name, c) => {
      const got = simulateFrom(c.anchor, c.state)
      expect(Math.abs(got.pHome - c.expected.pHome)).toBeLessThanOrEqual(fixture.tolerance)
      expect(Math.abs(got.pDraw - c.expected.pDraw)).toBeLessThanOrEqual(fixture.tolerance)
      expect(Math.abs(got.pAway - c.expected.pAway)).toBeLessThanOrEqual(fixture.tolerance)
      expect(Math.abs(got.expHomeGoals - c.expected.expHomeGoals)).toBeLessThanOrEqual(
        fixture.tolerance
      )
      expect(Math.abs(got.expAwayGoals - c.expected.expAwayGoals)).toBeLessThanOrEqual(
        fixture.tolerance
      )
      expect(got.topScorelines).toHaveLength(c.expected.topScorelines.length)
      got.topScorelines.forEach((line, i) => {
        expect(line.home).toBe(c.expected.topScorelines[i].home)
        expect(line.away).toBe(c.expected.topScorelines[i].away)
        expect(Math.abs(line.p - c.expected.topScorelines[i].p)).toBeLessThanOrEqual(
          fixture.tolerance
        )
      })
    }
  )

  it('produces proper distributions (probabilities sum to 1)', () => {
    for (const c of fixture.cases) {
      const got = simulateFrom(c.anchor, c.state)
      expect(got.pHome + got.pDraw + got.pAway).toBeCloseTo(1, 9)
      expect(got.pHome).toBeGreaterThanOrEqual(0)
      expect(got.pDraw).toBeGreaterThanOrEqual(0)
      expect(got.pAway).toBeGreaterThanOrEqual(0)
    }
  })
})

describe('engine kernel state semantics', () => {
  const anchor: MatchAnchor = { lambda: 1.55, mu: 1.15, rho: -0.05, gender: 'M' }

  it('minute-90 states are degenerate (the match is over)', () => {
    const won = simulateFrom(anchor, {
      minute: 90,
      homeGoals: 2,
      awayGoals: 1,
      homeReds: 0,
      awayReds: 0,
    })
    expect(won.pHome).toBeCloseTo(1, 12)
    expect(won.topScorelines[0]).toMatchObject({ home: 2, away: 1 })
    expect(won.topScorelines[0].p).toBeCloseTo(1, 12)

    const drawn = simulateFrom(anchor, {
      minute: 90,
      homeGoals: 1,
      awayGoals: 1,
      homeReds: 0,
      awayReds: 0,
    })
    expect(drawn.pDraw).toBeCloseTo(1, 12)
  })

  it('stoppage-time minutes clamp onto the 90-minute state', () => {
    const at90 = simulateFrom(anchor, {
      minute: 90,
      homeGoals: 1,
      awayGoals: 0,
      homeReds: 0,
      awayReds: 0,
    })
    const at94 = simulateFrom(anchor, {
      minute: 94,
      homeGoals: 1,
      awayGoals: 0,
      homeReds: 0,
      awayReds: 0,
    })
    expect(at94).toEqual(at90)
  })

  it('leading at 75 beats trailing at 75 for the same teams', () => {
    const leading = simulateFrom(anchor, {
      minute: 75,
      homeGoals: 1,
      awayGoals: 0,
      homeReds: 0,
      awayReds: 0,
    })
    const trailing = simulateFrom(anchor, {
      minute: 75,
      homeGoals: 0,
      awayGoals: 1,
      homeReds: 0,
      awayReds: 0,
    })
    expect(leading.pHome).toBeGreaterThan(trailing.pHome)
    expect(leading.pHome).toBeGreaterThan(0.75)
    expect(trailing.pAway).toBeGreaterThan(trailing.pHome)
  })

  it('goals cannot be un-scored: no scoreline below the current score', () => {
    const got = simulateFrom(anchor, {
      minute: 60,
      homeGoals: 2,
      awayGoals: 0,
      homeReds: 0,
      awayReds: 0,
    })
    for (const line of got.topScorelines) {
      expect(line.home).toBeGreaterThanOrEqual(2)
      expect(line.away).toBeGreaterThanOrEqual(0)
    }
    expect(got.expHomeGoals).toBeGreaterThanOrEqual(2)
  })
})

describe('anchor lookup (committed kernel artifact)', () => {
  it('returns null for unknown match ids', () => {
    expect(getMatchAnchor('definitely-not-a-warehouse-match-id')).toBeNull()
  })

  it('returns a well-formed anchor for a committed match id', () => {
    const artifact = JSON.parse(
      fs.readFileSync(
        path.join(process.cwd(), 'backend', 'data', 'engine', 'kernel.json'),
        'utf-8'
      )
    ) as { anchors: Record<string, number[]> }
    const someId = Object.keys(artifact.anchors)[0]
    const anchor = getMatchAnchor(someId)
    expect(anchor).not.toBeNull()
    expect(anchor?.lambda).toBeGreaterThan(0)
    expect(anchor?.mu).toBeGreaterThan(0)
    expect(anchor?.gender === 'M' || anchor?.gender === 'F').toBe(true)
  })
})
